// @generated automatically by Diesel CLI.
// This file will be generated by `diesel migration run`
// Placeholder until migrations are set up

diesel::table! {
    users (id) {
        id -> Uuid,
        email -> Varchar,
        hashed_password -> Varchar,
        display_name -> Nullable<Varchar>,
        is_active -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}
